# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow by cron
  schedule:
    - cron:  '0 17 * * *' # Every hour. Ref https://crontab.guru/examples.html

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup ruby and run
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: ruby main.rb
      
      # Setup node and build
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install
      - run: npm run build
      
      # Commit changes
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated: `date`"
          git push origin main
